name: CI

on: [pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.16.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.16.0
      uses: actions/setup-node@v1
      with:
        node-version: 8.16.0
    - name: Npm install and build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
